# Generated by Django 5.1.5 on 2025-01-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pictures',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='articles_images'),
        ),
    ]
