# Generated by Django 5.1.5 on 2025-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesPage', '0007_alter_order_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
