version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./app/:/usr/src/salesPageApp/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data: