version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/salesPageApp/app/staticfiles
      - media_volume:/usr/src/salesPageApp/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/salesPageApp/app/staticfiles
      - media_volume:/usr/src/salesPageApp/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: